apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami.yaml
  - ingress-nginx.yaml
  - cert-manager.yaml
  - sealed-secrets.yaml
  - elastic.yaml
  - fluent.yaml
  - grafana.yaml
  - influxdata.yaml
  - nfs-provisioner.yaml