apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - mosquitto-config.yaml
  - mosquitto-deployment.yaml
  - zigbee2mqtt-config.yaml
  - zigbee2mqtt-deployment.yaml
  - ingress.yaml
  - sealed-secrets.yaml
